<!DOCTYPE html>
<html lang="en">
<head>
    <title>HunterHint</title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="css/registration.css">

</head>
<body>
<div class="background">
    <div class="shape"></div>
    <div class="shape"></div>
</div>
<form class="form">
    <h3>Login Here</h3>

    <label for="username">Email</label>
    <input type="text" placeholder="email" id="username" name="email">

    <label for="password">Password</label>
    <input type="password" placeholder="Password" id="password" name="password">

    <button class="button">Log In</button>
    <div class="social">
        <div class="go"><a class="none" href="/registration">Регистрация</a></div>
    </div>
</form>
</body>
</html>
